<a href="https://colab.research.google.com/github/ojeidatasaved/Image-Processing-in-Python/blob/main/Copy_of__Data_processing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data processing


### Step 1 --  Import libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [ ]:
 os.getcwd()

'/content'

In [ ]:
#os.chdir(r"C:\Users\hp\Desktop\PYTHON and R Machine Learning Udemy\Machine Learning A-Z (Codes and Datasets)\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Python")

### Step 2 -- Import Dataset 

In [ ]:
data = pd.read_csv("Data.csv")
X = data.iloc[:, 0:2].values
y =data.iloc[:, 3].values

In [ ]:
print(X)


[['France' 44.0]
 ['Spain' 27.0]
 ['Germany' 30.0]
 ['Spain' 38.0]
 ['Germany' 40.0]
 ['France' 35.0]
 ['Spain' nan]
 ['France' 48.0]
 ['Germany' 50.0]
 ['France' 37.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


###  Step 2 -- Taking care of missing data


In [ ]:
# Replace using median 
mean = data["Salary"].mean()
data["Salary"].fillna(mean, inplace=True)


mean = data["Age"].median()
data["Age"].fillna(mean, inplace=True)
X = data.iloc[:, 0:3].values
y =data.iloc[:, 3].values

In [ ]:
print(data)

   Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  38.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes


In [ ]:
data.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

###  Step3---- Encoding Categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

### Always encode the independent variable  as seen below

In [ ]:
ct = ColumnTransformer(transformers =[("encoder",OneHotEncoder(),[0])], remainder ="passthrough")
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the dependent variable (Target class)

In [ ]:
from sklearn.preprocessing import LabelEncoder 
y = LabelEncoder().fit_transform(y)

In [ ]:
data.

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Step 4-- splitting the data into training and testing 

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


### Step 5 - Feature Selection

In [ ]:
from sklearn.preprocessing import StandardScaler

X_train[:,3:] = StandardScaler().fit_transform(X_train[:,3:])

X_test[:,3:] = StandardScaler().fit_transform(X_test[:,3:])

In [ ]:
print(X_train)


[[0.0 0.0 1.0 -0.28942984211696865 -1.0781259408412427]
 [0.0 1.0 0.0 0.0 -0.07013167641635401]
 [1.0 0.0 0.0 0.5788596842339373 0.6335624327104546]
 [0.0 0.0 1.0 -0.28942984211696865 -0.30786617274297895]
 [0.0 0.0 1.0 -1.8812939737602963 -1.4204636155515822]
 [1.0 0.0 0.0 1.1577193684678746 1.2326533634535488]
 [0.0 1.0 0.0 1.4471492105848434 1.5749910381638883]
 [1.0 0.0 0.0 -0.7235746052924217 -0.5646194287757336]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
